name: wholepipeline

on:
  push:
    branches: [ "master" ]

jobs:
    test_and_build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkoutv4

          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
              node-version: '18.13'  # Use the Node version compatible with your Angular appcrets.DOCKERHUB_USERNAME }}/github.repository_id:tag-test
        - name: Install Dependencies
          run: npm ci  # Faster than npm install, for CI environments

        - name: Run lint
          run: ng lint
       # - name: Run Angular Testser image
       #   run: npm run test

        - name: Build Docker Image
          run: docker builder build ./ -t testing

        - name: Log in to DockerHub
          run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

        - name: Tag Docker Image
          run: docker tag testing ${{ secrets.DOCKERHUB_USERNAME }}/testimage:tag-test

        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.20.0
          with:
              image-ref: 'docker.io/bachka512/testimage:tag-test'
              format: 'table'
              exit-code: '1'
              ignore-unfixed: true
              vuln-type: 'os,library'
              severity: 'CRITICAL,HIGH'

        - name: Push Docker Image
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/testimage:tag-test




