name: wholepipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push Container to docker.io
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: naming docker image
        run: docker tag testing ${{ secrets.DOCKERHUB_USERNAME }}/github.repository_id:tag-test
      - name: pushing docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/github.repository_id:tag-test
              



  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Get Docker Image
        run: echo "Pulling Docker image"  

      - name: Deploy 
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
        
      - name: echo
        if: ${{ cancelled() }}
        run: echo "cancelled" 
