name: wholepipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push Container to docker.io
        uses: GlueOps/github-actions-build-push-containers@v0.3.7
        with:
          registry: "docker.io"
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          Target_Reference: "tag-test"   

  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Get Docker Image
        run: echo "Pulling Docker image"  

      - name: Deploy 
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
        
      - name: echo
        if: ${{ cancelled() }}
        run: echo "cancelled" 
